'use client'

import { Check, ChevronRight, Edit, LayoutPanelTop, Lightbulb, type LucideIcon, Plus, Scale, Sparkles, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { toast } from 'sonner'

import { ProcessLoaderInline, type ProcessLoaderStep } from '@/components/process-loader-overlay'
import { SegmentedControl } from '@/components/segmented-control'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { LoadingSpinner, Spinner } from '@/components/ui/loading-spinner'
import { Tabs, TabsContent } from '@/components/ui/tabs'
import { AssessmentParametersTable } from '@/components/workflow-steps/assessment-parameters-table'
import { BidRecommendationCard } from '@/components/workflow-steps/bid-recommendation-card'
import { type BidAnalysis } from '@/libs/ai/bid-analysis'
import { WorkPackageContent } from '@/libs/repositories/work-package-content'
import { Requirement, WorkPackage } from '@/libs/repositories/work-packages'

type StrategyTab = 'requirements' | 'bid-decision' | 'win-strategy'
type StepState = 'pending' | 'loading' | 'complete'

const BID_DECISION_STEPS = [
  {
    id: 'requirements',
    label: 'Reviewing submission requirements',
    helper: 'Mapping mandatory vs optional asks',
  },
  {
    id: 'scoring',
    label: 'Scoring opportunity fit',
    helper: 'Balancing strengths and risks',
  },
  {
    id: 'recommendation',
    label: 'Crafting bid recommendation',
    helper: 'Highlighting strengths & concerns',
  },
] as const

const STRATEGY_TABS: Array<{
  value: StrategyTab
  label: string
  icon: LucideIcon
}> = [
  { value: 'requirements', label: 'Requirements', icon: LayoutPanelTop },
  { value: 'bid-decision', label: 'Bid / No-Bid', icon: Scale },
  { value: 'win-strategy', label: 'Win Strategy', icon: Lightbulb },
]

interface StrategyGenerationScreenProps {
  workPackageId: string
  workPackage: WorkPackage
  initialContent: WorkPackageContent | null
  onContinue: () => void
  onRefresh: () => Promise<void> | void
}

export function StrategyGenerationScreen({
  workPackageId,
  workPackage,
  initialContent,
  onContinue,
  onRefresh,
}: StrategyGenerationScreenProps) {
  const [winThemes, setWinThemes] = useState<string[]>(initialContent?.win_themes || [])
  const [bidAnalysis, setBidAnalysis] = useState<BidAnalysis | null>(initialContent?.bid_analysis || null)
  const [isGeneratingThemes, setIsGeneratingThemes] = useState(false)
  const [isGeneratingBidAnalysis, setIsGeneratingBidAnalysis] = useState(false)
  const [isGeneratingContent, setIsGeneratingContent] = useState(false)
  const [isContentGenerated, setIsContentGenerated] = useState(!!initialContent?.content)
  const [editingIndex, setEditingIndex] = useState<number | null>(null)
  const [editText, setEditText] = useState('')
  const [hasAutoGeneratedThemes, setHasAutoGeneratedThemes] = useState(() => winThemes.length > 0)
  const [hasAutoGeneratedBidAnalysis, setHasAutoGeneratedBidAnalysis] = useState(() => !!initialContent?.bid_analysis)
  const [activeSubTab, setActiveSubTab] = useState<StrategyTab>(
    initialContent?.bid_analysis ? 'bid-decision' : 'requirements'
  )
  const [bidLoaderStep, setBidLoaderStep] = useState(0)

  // Auto-generate win themes on mount if they don't exist
  useEffect(() => {
    if (winThemes.length === 0 && !isGeneratingThemes && !hasAutoGeneratedThemes) {
      setHasAutoGeneratedThemes(true)
      handleGenerateThemes()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (initialContent?.content) {
      setIsContentGenerated(true)
    }
  }, [initialContent?.content])

  useEffect(() => {
    if (initialContent?.win_themes?.length) {
      setWinThemes(initialContent.win_themes)
      setHasAutoGeneratedThemes(true)
    }
  }, [initialContent?.win_themes])

  useEffect(() => {
    if (initialContent?.bid_analysis) {
      setBidAnalysis(initialContent.bid_analysis)
      setHasAutoGeneratedBidAnalysis(true)
    }
  }, [initialContent?.bid_analysis])

  // Auto-generate bid analysis on mount if it doesn't exist
  useEffect(() => {
    if (!bidAnalysis && !isGeneratingBidAnalysis && !hasAutoGeneratedBidAnalysis) {
      setHasAutoGeneratedBidAnalysis(true)
      handleGenerateBidAnalysis()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (!isGeneratingBidAnalysis) {
      setBidLoaderStep(0)
      return
    }

    const timers = BID_DECISION_STEPS.map((_, index) =>
      setTimeout(() => {
        setBidLoaderStep(index)
      }, index * 2200)
    )

    return () => {
      timers.forEach(timer => clearTimeout(timer))
    }
  }, [isGeneratingBidAnalysis])

  const handleGenerateThemes = async () => {
    try {
      setIsGeneratingThemes(true)
      const res = await fetch(`/api/work-packages/${workPackageId}/win-themes`, {
        method: 'POST',
      })
      const data = await res.json()
      if (data.success) {
        setWinThemes(data.win_themes)
        toast.success('Win themes generated successfully')
        onRefresh() // Refresh parent data
      } else {
        toast.error(data.error || 'Failed to generate win themes')
      }
    } catch {
      toast.error('Failed to generate win themes')
    } finally {
      setIsGeneratingThemes(false)
    }
  }

  const handleEdit = (index: number) => {
    setEditingIndex(index)
    setEditText(winThemes[index])
  }

  const handleSaveEdit = (index: number) => {
    const updated = [...winThemes]
    updated[index] = editText
    setWinThemes(updated)
    setEditingIndex(null)
    setEditText('')
  }

  const handleDelete = (index: number) => {
    setWinThemes(winThemes.filter((_, i) => i !== index))
  }

  const handleAdd = () => {
    setWinThemes([...winThemes, 'New win theme...'])
    setEditingIndex(winThemes.length)
    setEditText('New win theme...')
  }

  const handleGenerateBidAnalysis = async () => {
    try {
      setIsGeneratingBidAnalysis(true)
      const res = await fetch(`/api/work-packages/${workPackageId}/bid-analysis`, {
        method: 'POST',
      })
      const data = await res.json()
      if (data.success) {
        setBidAnalysis(data.analysis)
        toast.success('Bid analysis generated successfully')
        onRefresh() // Refresh parent data
      } else {
        toast.error(data.error || 'Failed to generate bid analysis')
      }
    } catch {
      toast.error('Failed to generate bid analysis')
    } finally {
      setIsGeneratingBidAnalysis(false)
    }
  }

  const handleGenerateContent = async () => {
    try {
      setIsGeneratingContent(true)
      const res = await fetch(`/api/work-packages/${workPackageId}/generate-content`, {
        method: 'POST',
      })
      const data = await res.json()
      if (data.success) {
        setIsContentGenerated(true)
        toast.success('Content generated successfully')
        await onRefresh()
        onContinue()
      } else {
        toast.error(data.error || 'Failed to generate content')
      }
    } catch {
      toast.error('Failed to generate content')
    } finally {
      setIsGeneratingContent(false)
    }
  }

  // Prepare bid analysis data for display
  const assessmentCriteria = bidAnalysis?.criteria || []
  const totalScore = bidAnalysis?.totalScore || 0
  const bidRecommendation = bidAnalysis
    ? {
        recommendation: bidAnalysis.recommendation,
        reasoning: bidAnalysis.reasoning,
        strengths: bidAnalysis.strengths,
        concerns: bidAnalysis.concerns,
      }
    : null
  const hasGeneratedContent = isContentGenerated || !!initialContent?.content
  const isGenerateDisabled = winThemes.length === 0 || isGeneratingContent || isGeneratingThemes

  const requirementStatus: StepState = workPackage.requirements.length > 0 ? 'complete' : 'pending'
  const bidStatus: StepState = isGeneratingBidAnalysis
    ? 'loading'
    : bidAnalysis
      ? 'complete'
      : 'pending'
  const winStatus: StepState = isGeneratingThemes
    ? 'loading'
    : winThemes.length > 0
      ? 'complete'
      : 'pending'

  const processSteps: ProcessLoaderStep[] = [
    {
      id: 'requirements',
      label: requirementStatus === 'complete' ? 'Requirements ready' : 'Preparing requirements',
      helper:
        requirementStatus === 'complete'
          ? 'Submission criteria identified.'
          : 'Collecting mandatory asks and compliance points.',
    },
    {
      id: 'bid',
      label: bidStatus === 'complete' ? 'Bid / No-Bid ready' : 'Generating Bid / No-Bid analysis',
      helper:
        bidStatus === 'complete'
          ? 'Recommendation and scoring completed.'
          : 'Evaluating competitiveness and resourcing.',
    },
    {
      id: 'win',
      label: winStatus === 'complete' ? 'Win themes ready' : 'Developing win strategy',
      helper:
        winStatus === 'complete'
          ? 'Themes finalized for your response.'
          : 'Drafting differentiators and key messages.',
    },
  ]

  const stepStates: StepState[] = [requirementStatus, bidStatus, winStatus]
  const firstIncompleteIndex = stepStates.findIndex(state => state !== 'complete')
  const activeProcessStep = firstIncompleteIndex === -1 ? processSteps.length - 1 : firstIncompleteIndex

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_auto] md:items-start">
        <div className="space-y-4">
          <h2 className="text-2xl md:text-3xl font-bold">Tender Planning</h2>
          <p className="text-base text-muted-foreground">
            Review requirements, assess bid decision, develop win strategy, and generate content
          </p>
          <ProcessLoaderInline
            title="Preparing workspace"
            subtitle="We're setting up the context needed for this document."
            steps={processSteps}
            activeStep={activeProcessStep}
            iconLabel="TC"
            tone="warm"
            className="max-w-2xl"
          />
        </div>
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-end">
          {hasGeneratedContent && (
            <Button
              variant="outline"
              onClick={onContinue}
              disabled={isGeneratingContent}
              className="w-full sm:w-auto"
            >
              Continue in Editor
              <ChevronRight className="ml-2 size-4" />
            </Button>
          )}
          <Button
            onClick={handleGenerateContent}
            disabled={isGenerateDisabled}
            size="lg"
            className="w-full sm:w-auto"
          >
            {isGeneratingContent ? (
              <>
                <Spinner size="sm" className="mr-2 size-4 text-primary-foreground" />
                Generating Content
              </>
            ) : (
              <>
                <Sparkles className="mr-2 size-4" />
                Generate Content
              </>
            )}
          </Button>
        </div>
      </div>
      {!hasGeneratedContent && isGenerateDisabled && winThemes.length === 0 && !isGeneratingThemes && (
        <p className="text-xs text-muted-foreground">
          Generate or add win themes before creating content.
        </p>
      )}

      {/* Tab Navigation */}
      <SegmentedControl
        value={activeSubTab}
        onChange={value => setActiveSubTab(value as StrategyTab)}
        items={STRATEGY_TABS.map(tab => ({ value: tab.value, label: tab.label, icon: tab.icon }))}
        className="flex flex-wrap gap-2"
        fullWidth
      />

      <Tabs value={activeSubTab} onValueChange={(value) => setActiveSubTab(value as StrategyTab)} className="w-full">
        {/* Tab 1: Requirements */}
        <TabsContent value="requirements" className="mt-6 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Document Requirements</CardTitle>
              <p className="text-sm text-muted-foreground">
                Review the requirements identified for this {workPackage.document_type}
              </p>
            </CardHeader>
            <CardContent className="space-y-4">
              {workPackage.requirements.length === 0 ? (
                <p className="text-sm text-muted-foreground py-8 text-center">
                  No requirements specified for this work package
                </p>
              ) : (
                <div className="space-y-3">
                  {workPackage.requirements.map((req: Requirement, idx: number) => (
                    <div key={req.id} className="flex gap-3 p-4 border rounded-lg">
                      <span className="text-muted-foreground font-medium">{idx + 1}.</span>
                      <div className="flex-1 space-y-2">
                        <p className="text-sm">{req.text}</p>
                        <div className="flex items-center gap-2">
                          <Badge
                            variant={req.priority === 'mandatory' ? 'destructive' : 'secondary'}
                            className="text-xs"
                          >
                            {req.priority}
                          </Badge>
                          {req.source && (
                            <span className="text-xs text-muted-foreground">{req.source}</span>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Tab 2: Bid/No Bid Decision */}
        <TabsContent value="bid-decision" className="mt-6 space-y-6">
          <div className="relative min-h-[360px] space-y-6">
            {bidRecommendation ? (
              <>
                <AssessmentParametersTable
                  criteria={assessmentCriteria}
                  totalScore={totalScore}
                  incumbentStatus="unknown"
                />

                <BidRecommendationCard
                  recommendation={bidRecommendation.recommendation}
                  reasoning={bidRecommendation.reasoning}
                  strengths={bidRecommendation.strengths}
                  concerns={bidRecommendation.concerns}
                  onRegenerate={handleGenerateBidAnalysis}
                />
              </>
            ) : (
              <Card>
                <CardContent className="p-12 text-center">
                  <p className="text-sm text-muted-foreground mb-4">
                    {isGeneratingBidAnalysis
                      ? 'Analyzing opportunity...'
                      : 'No bid analysis available. Click to generate.'}
                  </p>
                  <Button onClick={handleGenerateBidAnalysis} disabled={isGeneratingBidAnalysis}>
                    <Sparkles className="mr-2 size-4" />
                    {isGeneratingBidAnalysis ? 'Working...' : 'Generate Bid Analysis'}
                  </Button>
                </CardContent>
              </Card>
            )}

            {isGeneratingBidAnalysis && (
              <BidDecisionLoader activeStep={bidLoaderStep} />
            )}
          </div>
        </TabsContent>

        {/* Tab 3: Win Strategy */}
        <TabsContent value="win-strategy" className="mt-6 space-y-6">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between gap-4">
                <div>
                  <CardTitle className="text-lg">Win Themes</CardTitle>
                  <p className="text-sm text-muted-foreground mt-1">
                    Identify 3-5 key messages that differentiate your proposal
                  </p>
                  <Badge variant="secondary" className="mt-3 text-xs">
                    {winThemes.length} themes captured
                  </Badge>
                </div>
                {winThemes.length > 0 && !isGeneratingThemes && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={handleGenerateThemes}
                    disabled={isGeneratingThemes}
                  >
                    <Sparkles className="mr-2 size-3" />
                    Regenerate All
                  </Button>
                )}
              </div>
            </CardHeader>
            <CardContent>
              {isGeneratingThemes ? (
                <LoadingSpinner size="sm" text="Generating win themes..." />
              ) : winThemes.length === 0 ? (
                <div className="text-center py-8">
                  <Sparkles className="mx-auto size-8 text-muted-foreground mb-3" />
                  <p className="text-sm text-muted-foreground mb-4">Generating win themes...</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {winThemes.map((theme, index) => (
                    <div key={index} className="border rounded-lg p-4">
                      {editingIndex === index ? (
                        <div className="flex gap-2">
                          <Input
                            value={editText}
                            onChange={e => setEditText(e.target.value)}
                            className="flex-1"
                          />
                          <Button size="sm" onClick={() => handleSaveEdit(index)}>
                            <Check className="size-4" />
                          </Button>
                        </div>
                      ) : (
                        <div className="flex items-start justify-between gap-3">
                          <div className="flex items-start gap-2 flex-1">
                            <div className="size-2 rounded-full bg-primary mt-2 shrink-0" />
                            <p className="text-sm">{theme}</p>
                          </div>
                          <div className="flex gap-1 shrink-0">
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => handleEdit(index)}
                              className="h-8 w-8 p-0"
                            >
                              <Edit className="size-4" />
                            </Button>
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => handleDelete(index)}
                              className="h-8 w-8 p-0 text-destructive hover:text-destructive"
                            >
                              <Trash2 className="size-4" />
                            </Button>
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                  <div className="flex gap-2 pt-2">
                    <Button variant="outline" onClick={handleAdd} size="sm" className="flex-1">
                      <Plus className="mr-2 size-4" />
                      Add Win Theme
                    </Button>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          {isGeneratingContent && (
            <Card className="border border-dashed border-primary/40 bg-primary/5">
              <CardContent className="p-6">
                <LoadingSpinner size="sm" text="Generating content... This may take 1-2 minutes." />
              </CardContent>
            </Card>
          )}

        </TabsContent>
      </Tabs>
    </div>
  )
}

function BidDecisionLoader({ activeStep }: { activeStep: number }) {
  return (
    <div className="absolute inset-0 z-20 flex items-center justify-center rounded-2xl border border-primary/30 bg-background/85 backdrop-blur-md px-6">
      <div className="w-full max-w-md space-y-4 text-center">
        <div className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">
          Bid / No-Bid
        </div>
        <h4 className="text-lg font-semibold">Preparing your recommendation</h4>
        <p className="text-sm text-muted-foreground">
          We&apos;re validating compliance, competitiveness, and resourcing before sharing guidance.
        </p>
        <div className="space-y-3 text-left">
          {BID_DECISION_STEPS.map((step, index) => {
            const status = activeStep > index ? 'complete' : activeStep === index ? 'active' : 'pending'
            return (
              <div key={step.id} className="flex items-start gap-3 rounded-xl border border-muted/60 bg-card/70 p-3">
                <BidDecisionStep status={status} />
                <div>
                  <p className="text-sm font-semibold">{step.label}</p>
                  <p className="text-xs text-muted-foreground">{step.helper}</p>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}

function BidDecisionStep({ status }: { status: 'pending' | 'active' | 'complete' }) {
  if (status === 'complete') {
    return (
      <span className="flex size-6 items-center justify-center rounded-full bg-emerald-100 text-emerald-600">
        <Check className="size-3.5" />
      </span>
    )
  }

  if (status === 'active') {
    return (
      <span className="flex size-6 items-center justify-center rounded-full border-2 border-primary">
        <Spinner size="sm" className="size-3.5" />
      </span>
    )
  }

  return <span className="size-6 rounded-full border-2 border-dashed border-muted-foreground/50" />
}
