'use client'

import { Check, ChevronRight, ClipboardList, Edit, Loader2, Plus, Sparkles, Target, Trash2, Trophy } from 'lucide-react'
import { useEffect, useState } from 'react'
import { toast } from 'sonner'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { LoadingSpinner } from '@/components/ui/loading-spinner'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { AssessmentParametersTable } from '@/components/workflow-steps/assessment-parameters-table'
import { BidRecommendationCard } from '@/components/workflow-steps/bid-recommendation-card'
import { type BidAnalysis } from '@/libs/ai/bid-analysis'
import { WorkPackageContent } from '@/libs/repositories/work-package-content'
import { Requirement, WorkPackage } from '@/libs/repositories/work-packages'

interface StrategyGenerationScreenProps {
  workPackageId: string
  workPackage: WorkPackage
  initialContent: WorkPackageContent | null
  onContinue: () => void
  onRefresh: () => void
}

export function StrategyGenerationScreen({
  workPackageId,
  workPackage,
  initialContent,
  onContinue,
  onRefresh,
}: StrategyGenerationScreenProps) {
  const [winThemes, setWinThemes] = useState<string[]>(initialContent?.win_themes || [])
  const [bidAnalysis, setBidAnalysis] = useState<BidAnalysis | null>(initialContent?.bid_analysis || null)
  const [isGeneratingThemes, setIsGeneratingThemes] = useState(false)
  const [isGeneratingBidAnalysis, setIsGeneratingBidAnalysis] = useState(false)
  const [isGeneratingContent, setIsGeneratingContent] = useState(false)
  const [isContentGenerated, setIsContentGenerated] = useState(!!initialContent?.content)
  const [editingIndex, setEditingIndex] = useState<number | null>(null)
  const [editText, setEditText] = useState('')
  const [hasAutoGeneratedThemes, setHasAutoGeneratedThemes] = useState(false)
  const [hasAutoGeneratedBidAnalysis, setHasAutoGeneratedBidAnalysis] = useState(false)

  // Auto-generate win themes on mount if they don't exist
  useEffect(() => {
    if (winThemes.length === 0 && !isGeneratingThemes && !hasAutoGeneratedThemes) {
      setHasAutoGeneratedThemes(true)
      handleGenerateThemes()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Auto-generate bid analysis on mount if it doesn't exist
  useEffect(() => {
    if (!bidAnalysis && !isGeneratingBidAnalysis && !hasAutoGeneratedBidAnalysis) {
      setHasAutoGeneratedBidAnalysis(true)
      handleGenerateBidAnalysis()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const handleGenerateThemes = async () => {
    try {
      setIsGeneratingThemes(true)
      const res = await fetch(`/api/work-packages/${workPackageId}/win-themes`, {
        method: 'POST',
      })
      const data = await res.json()
      if (data.success) {
        setWinThemes(data.win_themes)
        toast.success('Win themes generated successfully')
        onRefresh() // Refresh parent data
      } else {
        toast.error(data.error || 'Failed to generate win themes')
      }
    } catch {
      toast.error('Failed to generate win themes')
    } finally {
      setIsGeneratingThemes(false)
    }
  }

  const handleEdit = (index: number) => {
    setEditingIndex(index)
    setEditText(winThemes[index])
  }

  const handleSaveEdit = (index: number) => {
    const updated = [...winThemes]
    updated[index] = editText
    setWinThemes(updated)
    setEditingIndex(null)
    setEditText('')
  }

  const handleDelete = (index: number) => {
    setWinThemes(winThemes.filter((_, i) => i !== index))
  }

  const handleAdd = () => {
    setWinThemes([...winThemes, 'New win theme...'])
    setEditingIndex(winThemes.length)
    setEditText('New win theme...')
  }

  const handleGenerateBidAnalysis = async () => {
    try {
      setIsGeneratingBidAnalysis(true)
      const res = await fetch(`/api/work-packages/${workPackageId}/bid-analysis`, {
        method: 'POST',
      })
      const data = await res.json()
      if (data.success) {
        setBidAnalysis(data.analysis)
        toast.success('Bid analysis generated successfully')
        onRefresh() // Refresh parent data
      } else {
        toast.error(data.error || 'Failed to generate bid analysis')
      }
    } catch {
      toast.error('Failed to generate bid analysis')
    } finally {
      setIsGeneratingBidAnalysis(false)
    }
  }

  const handleGenerateContent = async () => {
    try {
      setIsGeneratingContent(true)
      const res = await fetch(`/api/work-packages/${workPackageId}/generate-content`, {
        method: 'POST',
      })
      const data = await res.json()
      if (data.success) {
        setIsContentGenerated(true)
        toast.success('Content generated successfully')
        setTimeout(() => {
          onContinue()
        }, 2000)
      } else {
        toast.error(data.error || 'Failed to generate content')
      }
    } catch {
      toast.error('Failed to generate content')
    } finally {
      setIsGeneratingContent(false)
    }
  }

  // Prepare bid analysis data for display
  const assessmentCriteria = bidAnalysis?.criteria || []
  const totalScore = bidAnalysis?.totalScore || 0
  const bidRecommendation = bidAnalysis
    ? {
        recommendation: bidAnalysis.recommendation,
        reasoning: bidAnalysis.reasoning,
        strengths: bidAnalysis.strengths,
        concerns: bidAnalysis.concerns,
      }
    : null

  // Show completion state
  if (isContentGenerated && isGeneratingContent === false && initialContent?.content) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Card className="max-w-md">
          <CardContent className="p-12 text-center">
            <div className="mx-auto size-16 rounded-full bg-green-100 dark:bg-green-900/20 flex items-center justify-center mb-4">
              <Check className="size-8 text-green-600 dark:text-green-400" />
            </div>
            <h3 className="text-xl font-semibold mb-2">Content Generated!</h3>
            <p className="text-muted-foreground">Redirecting to editor...</p>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl md:text-3xl font-bold">Tender Planning</h2>
        <p className="text-base text-muted-foreground">
          Review requirements, assess bid decision, develop win strategy, and generate content
        </p>
      </div>

      {/* Tab Navigation */}
      <Tabs defaultValue="bid-decision" className="w-full">
        <TabsList className="grid w-full grid-cols-3 h-auto p-1">
          <TabsTrigger value="requirements" className="flex items-center gap-2 py-3">
            <ClipboardList className="size-4" />
            <span>Requirements</span>
          </TabsTrigger>
          <TabsTrigger value="bid-decision" className="flex items-center gap-2 py-3">
            <Target className="size-4" />
            <span>Bid/No Bid</span>
          </TabsTrigger>
          <TabsTrigger value="win-strategy" className="flex items-center gap-2 py-3">
            <Trophy className="size-4" />
            <span>Win Strategy</span>
          </TabsTrigger>
        </TabsList>

        {/* Tab 1: Requirements */}
        <TabsContent value="requirements" className="mt-6 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Document Requirements</CardTitle>
              <p className="text-sm text-muted-foreground">
                Review the requirements identified for this {workPackage.document_type}
              </p>
            </CardHeader>
            <CardContent className="space-y-4">
              {workPackage.requirements.length === 0 ? (
                <p className="text-sm text-muted-foreground py-8 text-center">
                  No requirements specified for this work package
                </p>
              ) : (
                <div className="space-y-3">
                  {workPackage.requirements.map((req: Requirement, idx: number) => (
                    <div key={req.id} className="flex gap-3 p-4 border rounded-lg">
                      <span className="text-muted-foreground font-medium">{idx + 1}.</span>
                      <div className="flex-1 space-y-2">
                        <p className="text-sm">{req.text}</p>
                        <div className="flex items-center gap-2">
                          <Badge
                            variant={req.priority === 'mandatory' ? 'destructive' : 'secondary'}
                            className="text-xs"
                          >
                            {req.priority}
                          </Badge>
                          {req.source && (
                            <span className="text-xs text-muted-foreground">{req.source}</span>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Tab 2: Bid/No Bid Decision */}
        <TabsContent value="bid-decision" className="mt-6 space-y-6">
          {isGeneratingBidAnalysis ? (
            <Card>
              <CardContent className="p-12">
                <LoadingSpinner size="md" text="Generating bid analysis... This may take 1-2 minutes." />
              </CardContent>
            </Card>
          ) : bidRecommendation ? (
            <>
              {/* Assessment Parameters Table */}
              <AssessmentParametersTable
                criteria={assessmentCriteria}
                totalScore={totalScore}
                incumbentStatus="unknown"
              />

              {/* Bid Decision Recommendation */}
              <BidRecommendationCard
                recommendation={bidRecommendation.recommendation}
                reasoning={bidRecommendation.reasoning}
                strengths={bidRecommendation.strengths}
                concerns={bidRecommendation.concerns}
                onRegenerate={handleGenerateBidAnalysis}
              />
            </>
          ) : (
            <Card>
              <CardContent className="p-12 text-center">
                <p className="text-sm text-muted-foreground mb-4">
                  No bid analysis available. Click to generate.
                </p>
                <Button onClick={handleGenerateBidAnalysis}>
                  <Sparkles className="mr-2 size-4" />
                  Generate Bid Analysis
                </Button>
              </CardContent>
            </Card>
          )}
        </TabsContent>

        {/* Tab 3: Win Strategy */}
        <TabsContent value="win-strategy" className="mt-6 space-y-6">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-lg">Win Themes</CardTitle>
                  <p className="text-sm text-muted-foreground mt-1">
                    Identify 3-5 key messages that differentiate your proposal
                  </p>
                </div>
                {winThemes.length > 0 && !isGeneratingThemes && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={handleGenerateThemes}
                    disabled={isGeneratingThemes}
                  >
                    <Sparkles className="mr-2 size-3" />
                    Regenerate All
                  </Button>
                )}
              </div>
            </CardHeader>
            <CardContent>
              {isGeneratingThemes ? (
                <LoadingSpinner size="sm" text="Generating win themes..." />
              ) : winThemes.length === 0 ? (
                <div className="text-center py-8">
                  <Sparkles className="mx-auto size-8 text-muted-foreground mb-3" />
                  <p className="text-sm text-muted-foreground mb-4">Generating win themes...</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {winThemes.map((theme, index) => (
                    <div key={index} className="border rounded-lg p-4">
                      {editingIndex === index ? (
                        <div className="flex gap-2">
                          <Input
                            value={editText}
                            onChange={e => setEditText(e.target.value)}
                            className="flex-1"
                          />
                          <Button size="sm" onClick={() => handleSaveEdit(index)}>
                            <Check className="size-4" />
                          </Button>
                        </div>
                      ) : (
                        <div className="flex items-start justify-between gap-3">
                          <div className="flex items-start gap-2 flex-1">
                            <div className="size-2 rounded-full bg-primary mt-2 shrink-0" />
                            <p className="text-sm">{theme}</p>
                          </div>
                          <div className="flex gap-1 shrink-0">
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => handleEdit(index)}
                              className="h-8 w-8 p-0"
                            >
                              <Edit className="size-4" />
                            </Button>
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => handleDelete(index)}
                              className="h-8 w-8 p-0 text-destructive hover:text-destructive"
                            >
                              <Trash2 className="size-4" />
                            </Button>
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                  <div className="flex gap-2 pt-2">
                    <Button variant="outline" onClick={handleAdd} size="sm" className="flex-1">
                      <Plus className="mr-2 size-4" />
                      Add Win Theme
                    </Button>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Content Generation Card - Only on Win Strategy Tab */}
          <Card className="border-2 border-primary/20">
            <CardHeader>
              <CardTitle className="text-lg">Content Generation</CardTitle>
              <p className="text-sm text-muted-foreground">
                Ready to generate your {workPackage.document_type}
              </p>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-3 gap-4">
                <div className="space-y-1">
                  <p className="text-xs text-muted-foreground">Document Type</p>
                  <p className="text-sm font-medium">{workPackage.document_type}</p>
                </div>
                <div className="space-y-1">
                  <p className="text-xs text-muted-foreground">Requirements</p>
                  <Badge variant="outline">{workPackage.requirements.length} total</Badge>
                </div>
                <div className="space-y-1">
                  <p className="text-xs text-muted-foreground">Win Themes</p>
                  <Badge variant="outline">{winThemes.length} themes</Badge>
                </div>
              </div>

              {isGeneratingContent && (
                <Card className="bg-muted/50 border-muted">
                  <CardContent className="p-4">
                    <LoadingSpinner
                      size="md"
                      text="Generating content... This may take 1-2 minutes."
                    />
                  </CardContent>
                </Card>
              )}

              <div className="space-y-3">
                <Button
                  onClick={handleGenerateContent}
                  disabled={winThemes.length === 0 || isGeneratingContent || isGeneratingThemes}
                  size="lg"
                  className="w-full"
                >
                  {isGeneratingContent ? (
                    <>
                      <Loader2 className="mr-2 size-4 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="mr-2 size-4" />
                      Generate Content
                    </>
                  )}
                </Button>
                {winThemes.length === 0 && !isGeneratingThemes && (
                  <p className="text-xs text-muted-foreground text-center">
                    Waiting for win themes to be generated...
                  </p>
                )}
                {initialContent?.content && !isGeneratingContent && (
                  <Button onClick={onContinue} variant="outline" size="lg" className="w-full">
                    Continue to Edit
                    <ChevronRight className="ml-2 size-4" />
                  </Button>
                )}
              </div>

              <div className="text-xs text-muted-foreground border-t pt-3">
                <p>Estimated generation time: 2-3 minutes</p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}
